### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by KurtDeGreeff** [dmauser/PS-Network-Capture#1]
Thanks for this simple great approach for capturing network traffic

However I'm not getting any visual output when analyzing the ETL afterwards. One remark I've seen : 
In your script you're using 'Add-NetEventPacketCaptureProvider -SessionName Session1' but you never specify the provider GUID..should I specify it somewhere else? Many thanks

**Comment by dmauser** [comment]
Sorry for the delay answering this but I think you have already figured out.
In this case there's no need to add provider ID because the NDIS capture provider is already built in to Add-NetEventPacketCaptureProvider.
